---------------------------------------------- Unique identifiability Conjecture 
-- author: annachiara korchmaros
-- last update: December 22, 2022
-- check if the degree of the ideal generated by 7 polynomials is 0 and dimension is 2
-- the ideal generated by the polynomials obtained from rational equations for seven unambiguous beads after moving all terms to one side and clearing the denominators. 


R = QQ[x1,x2,x3,y1,y2,y3]; -- rational points

SevenEq = nTrails -> (
    for trail from 1 to nTrails do (
	 -- choose A,B,C,D,E,F,G points nTrials times
    	a1 = random(QQ); a2 = random(QQ); a3 = random(QQ); -- point coordinates
	b1 = random(QQ); b2 = random(QQ); b3 = random(QQ);
	c1 = random(QQ); c2 = random(QQ); c3 = random(QQ);
	d1 = random(QQ); d2 = random(QQ); d3 = random(QQ);
	e1 = random(QQ); e2 = random(QQ); e3 = random(QQ);
	f1 = random(QQ); f2 = random(QQ); f3 = random(QQ);
	g1 = random(QQ); g2 = random(QQ); g3 = random(QQ);
	-- random choose two more points X and Y 
	X1 = random(QQ); X2 = random(QQ); X3 = random(QQ);
	Y1 = random(QQ); Y2 = random(QQ); Y3 = random(QQ);
	-- check if nocoplanar ie general position
	M = matrix{{a1,a2,a3},{b1,b2,b3},{c1,c2,c3},{d1,d2,d3},{e1,e2,e3},{f1,f2,f3},{g1,g2,g3},{X1,X2,X3},{Y1,Y2,Y3}};
	rankM = rank M;
	-- compute frequencies of HI-C matrix
	ka = 1/((X1-a1)^2 + (X2-a2)^2 + (X3-a3)^2)+ 1/((Y1-a1)^2 + (Y2-a2)^2 + (Y3-a3)^2);
        kb = 1/((X1-b1)^2 + (X2-b2)^2 + (X3-b3)^2)+1/((Y1-b1)^2 + (Y2-b2)^2 + (Y3-b3)^2);
        kc = 1/((X1-c1)^2 + (X2-c2)^2 + (X3-c3)^2)+1/((Y1-c1)^2 + (Y2-c2)^2 + (Y3-c3)^2);
        kd = 1/((X1-d1)^2 + (X2-d2)^2 + (X3-d3)^2)+1/((Y1-d1)^2 + (Y2-d2)^2 + (Y3-d3)^2);
	ke = 1/((X1-e1)^2 + (X2-e2)^2 + (X3-e3)^2)+1/((Y1-e1)^2 + (Y2-e2)^2 + (Y3-e3)^2);
	kf = 1/((X1-f1)^2 + (X2-f2)^2 + (X3-f3)^2)+1/((Y1-f1)^2 + (Y2-f2)^2 + (Y3-f3)^2);
	kg = 1/((X1-g1)^2 + (X2-g2)^2 + (X3-g3)^2)+1/((Y1-g1)^2 + (Y2-g2)^2 + (Y3-g3)^2);
        -- compute polynomials and ideal 
	Ga = ka*((x1-a1)^2 + (x2-a2)^2 + (x3-a3)^2)*((y1-a1)^2 + (y2-a2)^2 + (y3-a3)^2)-((x1-a1)^2 + (x2-a2)^2 + (x3-a3)^2 + (y1-a1)^2 + (y2-a2)^2 + (y3-a3)^2);
	Gb = kb*((x1-b1)^2 + (x2-b2)^2 + (x3-b3)^2)*((y1-b1)^2 + (y2-b2)^2 + (y3-b3)^2)-((x1-b1)^2 + (x2-b2)^2 + (x3-b3)^2 + (y1-b1)^2 + (y2-b2)^2 + (y3-b3)^2);
	Gc = kc*((x1-c1)^2 + (x2-c2)^2 + (x3-c3)^2)*((y1-c1)^2 + (y2-c2)^2 + (y3-c3)^2)-((x1-c1)^2 + (x2-c2)^2 + (x3-c3)^2 + (y1-c1)^2 + (y2-c2)^2 + (y3-c3)^2);
	Gd = kd*((x1-d1)^2 + (x2-d2)^2 + (x3-d3)^2)*((y1-d1)^2 + (y2-d2)^2 + (y3-d3)^2)-((x1-d1)^2 + (x2-d2)^2 + (x3-d3)^2 + (y1-d1)^2 + (y2-d2)^2 + (y3-d3)^2);
	Ge = ke*((x1-e1)^2 + (x2-e2)^2 + (x3-e3)^2)*((y1-e1)^2 + (y2-e2)^2 + (y3-e3)^2)-((x1-e1)^2 + (x2-e2)^2 + (x3-e3)^2 + (y1-e1)^2 + (y2-e2)^2 + (y3-e3)^2);
	Gf = kf*((x1-f1)^2 + (x2-f2)^2 + (x3-f3)^2)*((y1-f1)^2 + (y2-f2)^2 + (y3-f3)^2)-((x1-f1)^2 + (x2-f2)^2 + (x3-f3)^2 + (y1-f1)^2 + (y2-f2)^2 + (y3-f3)^2);
	Gg = kg*((x1-g1)^2 + (x2-g2)^2 + (x3-g3)^2)*((y1-g1)^2 + (y2-g2)^2 + (y3-g3)^2)-((x1-g1)^2 + (x2-g2)^2 + (x3-g3)^2 + (y1-g1)^2 + (y2-g2)^2 + (y3-g3)^2);
	I = ideal(Ga,Gb,Gc,Gd,Ge,Gf,Gg);
	dm = dim I;
	dg = degree I;
	"7equations_output"  << "dimension = "<<dm<<";" << endl;
	"7equations_output"  << "degree = "<<dg<<";" << endl;
	"7equations_output"  << "rank = "<<rankM<<";" << endl;
     	);
        "7equations_output" << "--end--"<< endl << close;
	return  << "--end-- ";
	)	
		
		
	     
      


